# train options
batch_size: 256
start_epoch: 0
epochs: 30
pretrain: False
type: "separate" # in the supervised setting, decision between joint or separate model
train_csv: "/media/storagecube/markus/project/data/train.csv"
val_csv: "/media/storagecube/markus/project/data/val.csv"
test_csv: "/media/storagecube/markus/project/data/test.csv"
loss_func: "classification"
fusion: "concat"
bigEarthPthLMDB_S2: "/media/storagecube/markus/project/data/BigEarth_Serbia_Summer_S2.lmdb"
bigEarthPthLMDB_S1: "/media/storagecube/markus/project/data/BigEarth_Serbia_Summer_S1.lmdb"
num_cpu: 40

# model options
name: "test"
n_features: 2048  # features after the resnet 50 layer
projection_dim: 128 # in this case needed for the classification loss fc layer
out_channels: 32 # only used in joint mode for the Resnet model out-channels coming from Conv1

# loss options
optimizer: "adam"
learning_rate: 0.0001
weight_decay: 0.0
scheduler: False # optional not used right now
temperature: 0.1 # for NXT Loss


# reload options
state_dict: "/media/storagecube/markus/project/logs/test/separate_concat_s2_sanity/checkpoints_model_best.pth.tar" # set to the directory containing `checkpoint_##.tar`



## logging options

logging_params:
  save_dir: "logs/"
  name: "separate_concat_s2_sanity" # maybe a special name




### change fusion, loggin_params, and !!!!!!!!!!! state_dict!!!!!!!!
