

# train options

batch_size: 32
start_epoch: 0
epochs: 2
pretrain: False
type: "joint" # in the supervised setting, decision between joint or seperate model
train_csv: "C:/Users/Markus/Desktop/splits_mm_serbia/train.csv"
val_csv: "C:/Users/Markus/Desktop/splits_mm_serbia/val.csv"
test_csv: "C:/Users/Markus/Desktop/splits_mm_serbia/test.csv"
loss_func: "classification"
fusion: "avg"

# model options
name: "Resnet50"
n_features: 2048  # features after the resnet 50 layer
projection_dim: 128 # "[...] to project the representation to a n-dimensional latent space"
out_channels: 32 # only used in joint mode for the Resnet model out-channels coming from Conv1

# loss options
optimizer: "sgd"
learning_rate: 0.003
weight_decay: 0.0
scheduler_gamma: 0.9
temperature: 0 # for NXT Loss



# reload options
model_path: "save" # set to the directory containing `checkpoint_##.tar` 
epoch_num: 100 # set to checkpoint number
reload: False


## logging options

logging_params:
  save_dir: "logs/"
  name: "first_test" # maybe a special name



